package io.mohoromitch.goblast;

import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;

/**
 * A list of queries taken from the previous assignments.
 * Created by Frank on 2016-11-24.
 */
public class Queries {
	public static final String P_TABLES =
		"INSERT INTO PLAYERS (ID, FIRST_NAME, LAST_NAME) VALUES (0, 'Cady', 'Heron');\n" +
			"INSERT INTO PLAYERS (ID, FIRST_NAME, LAST_NAME) VALUES (1, 'Regina', 'George');\n" +
			"INSERT INTO PLAYERS (ID, FIRST_NAME, LAST_NAME) VALUES (2, 'Gretchen', 'Wieners');\n" +
			"INSERT INTO PLAYERS (ID, FIRST_NAME, LAST_NAME) VALUES (3, 'Janis', 'Ian');\n" +
			"INSERT INTO PLAYERS (ID, FIRST_NAME, LAST_NAME) VALUES (4, 'Karen', 'Smith');\n" +
			"INSERT INTO PLAYERS (ID, FIRST_NAME, LAST_NAME) VALUES (5, 'Kevin', 'Gnapoor');\n" +
			"INSERT INTO PLAYERS (ID, FIRST_NAME, LAST_NAME) VALUES (6, 'Trang', 'Pak');\n" +
			"INSERT INTO PLAYERS (ID, FIRST_NAME, LAST_NAME) VALUES (7, 'Aaron', 'Samuels');\n" +
			"INSERT INTO PLAYERS (ID, FIRST_NAME, LAST_NAME) VALUES (8, 'Glenn', 'Cocoo');\n" +
			"INSERT INTO PLAYERS (ID, FIRST_NAME, LAST_NAME) VALUES (9, 'Shane', 'Oman');\n" +
			"INSERT INTO PLAYERS (ID, FIRST_NAME, LAST_NAME) VALUES (10, 'Ms.', 'Norbury');\n" +
			"INSERT INTO PLAYERS (ID, FIRST_NAME, LAST_NAME) VALUES (11, 'Mrs.', 'George');\n" +
			"INSERT INTO PLAYERS (ID, FIRST_NAME, LAST_NAME) VALUES (12, 'Caroline', 'Krafft');\n" +
			"INSERT INTO PLAYERS (ID, FIRST_NAME, LAST_NAME) VALUES (13, 'Coach', 'Carr');\n" +
			"INSERT INTO PLAYERS (ID, FIRST_NAME, LAST_NAME) VALUES (14, 'Principal', 'Duvall');\n" +
			"INSERT INTO PLAYERS (ID, FIRST_NAME, LAST_NAME) VALUES (15, 'Emma', 'Gerber');\n" +
			"INSERT INTO PLAYERS (ID, FIRST_NAME, LAST_NAME) VALUES (16, 'Taylor', 'Wedell');\n" +
			"INSERT INTO PLAYERS (ID, FIRST_NAME, LAST_NAME) VALUES (17, 'Kristen', 'Hadley');\n" +
			"INSERT INTO PLAYERS (ID, FIRST_NAME, LAST_NAME) VALUES (18, 'Dawn', 'Schweitzer');\n" +
			"INSERT INTO PLAYERS (ID, FIRST_NAME, LAST_NAME) VALUES (19, 'Tim', 'Pak');\n" +
			"INSERT INTO PLAYERS (ID, FIRST_NAME, LAST_NAME) VALUES (20, 'Damian', 'Leigh');\n" +
			"\n" +
			"INSERT INTO TEAMS (ID, NAME) VALUES (1, 'The Plastics');\n" +
			"INSERT INTO TEAMS (ID, NAME) VALUES (2, 'The Mathletes');\n" +
			"\n" +
			"INSERT INTO SEASONS (ID, YEAR, TYPE) VALUES (1, 2015, 'regular');\n" +
			"INSERT INTO SEASONS (ID, YEAR, TYPE) VALUES (2, 2016, 'regular');\n" +
			"\n" +
			"INSERT INTO PLAYS_FOR (PLAYER_ID, SEASON_ID, TEAM_ID)  VALUES (0, 1, 1);\n" +
			"INSERT INTO PLAYS_FOR (PLAYER_ID, SEASON_ID, TEAM_ID)  VALUES (1, 1, 1);\n" +
			"INSERT INTO PLAYS_FOR (PLAYER_ID, SEASON_ID, TEAM_ID)  VALUES (2, 1, 1);\n" +
			"INSERT INTO PLAYS_FOR (PLAYER_ID, SEASON_ID, TEAM_ID)  VALUES (3, 1, 1);\n" +
			"INSERT INTO PLAYS_FOR (PLAYER_ID, SEASON_ID, TEAM_ID)  VALUES (4, 1, 1);\n" +
			"INSERT INTO PLAYS_FOR (PLAYER_ID, SEASON_ID, TEAM_ID)  VALUES (5, 1, 1);\n" +
			"INSERT INTO PLAYS_FOR (PLAYER_ID, SEASON_ID, TEAM_ID)  VALUES (6, 1, 1);\n" +
			"INSERT INTO PLAYS_FOR (PLAYER_ID, SEASON_ID, TEAM_ID)  VALUES (7, 1, 1);\n" +
			"INSERT INTO PLAYS_FOR (PLAYER_ID, SEASON_ID, TEAM_ID)  VALUES (8, 1, 1);\n" +
			"INSERT INTO PLAYS_FOR (PLAYER_ID, SEASON_ID, TEAM_ID)  VALUES (9, 1, 1);\n" +
			"\n" +
			"INSERT INTO PLAYS_FOR (PLAYER_ID, SEASON_ID, TEAM_ID)  VALUES (10, 1, 2);\n" +
			"INSERT INTO PLAYS_FOR (PLAYER_ID, SEASON_ID, TEAM_ID)  VALUES (11, 1, 2);\n" +
			"INSERT INTO PLAYS_FOR (PLAYER_ID, SEASON_ID, TEAM_ID)  VALUES (12, 1, 2);\n" +
			"INSERT INTO PLAYS_FOR (PLAYER_ID, SEASON_ID, TEAM_ID)  VALUES (13, 1, 2);\n" +
			"INSERT INTO PLAYS_FOR (PLAYER_ID, SEASON_ID, TEAM_ID)  VALUES (14, 1, 2);\n" +
			"INSERT INTO PLAYS_FOR (PLAYER_ID, SEASON_ID, TEAM_ID)  VALUES (15, 1, 2);\n" +
			"INSERT INTO PLAYS_FOR (PLAYER_ID, SEASON_ID, TEAM_ID)  VALUES (16, 1, 2);\n" +
			"INSERT INTO PLAYS_FOR (PLAYER_ID, SEASON_ID, TEAM_ID)  VALUES (17, 1, 2);\n" +
			"INSERT INTO PLAYS_FOR (PLAYER_ID, SEASON_ID, TEAM_ID)  VALUES (18, 1, 2);\n" +
			"INSERT INTO PLAYS_FOR (PLAYER_ID, SEASON_ID, TEAM_ID)  VALUES (19, 1, 2);\n" +
			"INSERT INTO PLAYS_FOR (PLAYER_ID, SEASON_ID, TEAM_ID)  VALUES (20, 1, 2);\n" +
			"\n" +
			"INSERT INTO PLAYS_FOR (PLAYER_ID, SEASON_ID, TEAM_ID)  VALUES (0, 2, 1);\n" +
			"INSERT INTO PLAYS_FOR (PLAYER_ID, SEASON_ID, TEAM_ID)  VALUES (1, 2, 1);\n" +
			"INSERT INTO PLAYS_FOR (PLAYER_ID, SEASON_ID, TEAM_ID)  VALUES (2, 2, 1);\n" +
			"INSERT INTO PLAYS_FOR (PLAYER_ID, SEASON_ID, TEAM_ID)  VALUES (3, 2, 1);\n" +
			"INSERT INTO PLAYS_FOR (PLAYER_ID, SEASON_ID, TEAM_ID)  VALUES (4, 2, 1);\n" +
			"INSERT INTO PLAYS_FOR (PLAYER_ID, SEASON_ID, TEAM_ID)  VALUES (5, 2, 1);\n" +
			"INSERT INTO PLAYS_FOR (PLAYER_ID, SEASON_ID, TEAM_ID)  VALUES (6, 2, 1);\n" +
			"INSERT INTO PLAYS_FOR (PLAYER_ID, SEASON_ID, TEAM_ID)  VALUES (7, 2, 2);\n" +
			"INSERT INTO PLAYS_FOR (PLAYER_ID, SEASON_ID, TEAM_ID)  VALUES (8, 2, 2);\n" +
			"INSERT INTO PLAYS_FOR (PLAYER_ID, SEASON_ID, TEAM_ID)  VALUES (9, 2, 2);\n" +
			"\n" +
			"INSERT INTO PLAYS_FOR (PLAYER_ID, SEASON_ID, TEAM_ID)  VALUES (10, 2, 1);\n" +
			"INSERT INTO PLAYS_FOR (PLAYER_ID, SEASON_ID, TEAM_ID)  VALUES (11, 2, 1);\n" +
			"INSERT INTO PLAYS_FOR (PLAYER_ID, SEASON_ID, TEAM_ID)  VALUES (12, 2, 2);\n" +
			"INSERT INTO PLAYS_FOR (PLAYER_ID, SEASON_ID, TEAM_ID)  VALUES (13, 2, 2);\n" +
			"INSERT INTO PLAYS_FOR (PLAYER_ID, SEASON_ID, TEAM_ID)  VALUES (14, 2, 2);\n" +
			"INSERT INTO PLAYS_FOR (PLAYER_ID, SEASON_ID, TEAM_ID)  VALUES (15, 2, 1);\n" +
			"INSERT INTO PLAYS_FOR (PLAYER_ID, SEASON_ID, TEAM_ID)  VALUES (16, 2, 1);\n" +
			"INSERT INTO PLAYS_FOR (PLAYER_ID, SEASON_ID, TEAM_ID)  VALUES (17, 2, 2);\n" +
			"INSERT INTO PLAYS_FOR (PLAYER_ID, SEASON_ID, TEAM_ID)  VALUES (18, 2, 2);\n" +
			"INSERT INTO PLAYS_FOR (PLAYER_ID, SEASON_ID, TEAM_ID)  VALUES (19, 2, 2);\n" +
			"INSERT INTO PLAYS_FOR (PLAYER_ID, SEASON_ID, TEAM_ID)  VALUES (20, 2, 2);\n" +
			"\n" +
			"\n" +
			"INSERT INTO GAMES (ID, HOME_TEAM_ID, VISITOR_TEAM_ID, SEASON_ID, HOME_SCORE, VISITOR_SCORE, GAME_LOCATION, GAME_DATE)\n" +
			"VALUES (1, 1, 2, 1, 5, 2, 'Rosedale Park', TO_DATE('15-OCT-4 18:30','YY-MON-DD HH24:MI'));\n" +
			"INSERT INTO GAMES (ID, HOME_TEAM_ID, VISITOR_TEAM_ID, SEASON_ID, HOME_SCORE, VISITOR_SCORE, GAME_LOCATION, GAME_DATE)\n" +
			"VALUES (2, 1, 2, 1, 3, 6, 'Christie Pits Park', TO_DATE('15-OCT-11 18:30','YY-MON-DD HH24:MI'));\n" +
			"INSERT INTO GAMES (ID, HOME_TEAM_ID, VISITOR_TEAM_ID, SEASON_ID, HOME_SCORE, VISITOR_SCORE, GAME_LOCATION, GAME_DATE)\n" +
			"VALUES (3, 2, 1, 1, 2, 2, 'Highview Park', TO_DATE('15-OCT-18 18:30','YY-MON-DD HH24:MI'));\n" +
			"INSERT INTO GAMES (ID, HOME_TEAM_ID, VISITOR_TEAM_ID, SEASON_ID, HOME_SCORE, VISITOR_SCORE, GAME_LOCATION, GAME_DATE)\n" +
			"VALUES (4, 2, 1, 1, 3, 2, 'Highview Park', TO_DATE('15-OCT-25 18:30','YY-MON-DD HH24:MI'));\n" +
			"\n" +
			"INSERT INTO GAMES (ID, HOME_TEAM_ID, VISITOR_TEAM_ID, SEASON_ID, HOME_SCORE, VISITOR_SCORE, GAME_LOCATION, GAME_DATE)\n" +
			"VALUES (5, 1, 2, 2, 8, 2, 'Rosedale Park', TO_DATE('16-OCT-4 18:30','YY-MON-DD HH24:MI'));\n" +
			"INSERT INTO GAMES (ID, HOME_TEAM_ID, VISITOR_TEAM_ID, SEASON_ID, HOME_SCORE, VISITOR_SCORE, GAME_LOCATION, GAME_DATE)\n" +
			"VALUES (6, 1, 2, 2, 2, 3, 'Rosedale Park', TO_DATE('16-OCT-12 18:30','YY-MON-DD HH24:MI'));\n" +
			"INSERT INTO GAMES (ID, HOME_TEAM_ID, VISITOR_TEAM_ID, SEASON_ID, HOME_SCORE, VISITOR_SCORE, GAME_LOCATION, GAME_DATE)\n" +
			"VALUES (7, 1, 2, 2, 2, 4, 'Rosedale Park', TO_DATE('16-OCT-18 18:30','YY-MON-DD HH24:MI'));\n" +
			"INSERT INTO GAMES (ID, HOME_TEAM_ID, VISITOR_TEAM_ID, SEASON_ID, HOME_SCORE, VISITOR_SCORE, GAME_LOCATION, GAME_DATE)\n" +
			"VALUES (8, 1, 2, 2, 1, 5, 'Rosedale Park', TO_DATE('16-OCT-25 18:30', 'YY-MON-DD HH24:MI'));\n" +
			"\n" +
			"\n" +
			"-- INSERT INTO STATISTICS (PLAYER_ID, GAME_ID, AB, H, R, RBI, \"1B\", \"2B\", \"3B\", HR) VALUES\n" +
			"--game 1\n" +
			"INSERT INTO STATISTICS (ID, AB, H, R, RBI, \"1B\", \"2B\", \"3B\", HR) VALUES (0, 7, 2, 1, 1, 0, 0, 0, 0);\n" +
			"INSERT INTO STATISTICS (ID, AB, H, R, RBI, \"1B\", \"2B\", \"3B\", HR) VALUES (1, 7, 3, 2, 3, 0, 0, 1, 1);\n" +
			"INSERT INTO STATISTICS (ID, AB, H, R, RBI, \"1B\", \"2B\", \"3B\", HR) VALUES (2, 7, 4, 0, 0, 0, 1, 0, 0);\n" +
			"INSERT INTO STATISTICS (ID, AB, H, R, RBI, \"1B\", \"2B\", \"3B\", HR) VALUES (3, 7, 5, 0, 0, 0, 0, 0, 0);\n" +
			"INSERT INTO STATISTICS (ID, AB, H, R, RBI, \"1B\", \"2B\", \"3B\", HR) VALUES (4, 6, 3, 1, 0, 1, 2, 0, 0);\n" +
			"INSERT INTO STATISTICS (ID, AB, H, R, RBI, \"1B\", \"2B\", \"3B\", HR) VALUES (5, 6, 2, 0, 0, 0, 0, 0, 0);\n" +
			"INSERT INTO STATISTICS (ID, AB, H, R, RBI, \"1B\", \"2B\", \"3B\", HR) VALUES (6, 6, 3, 0, 0, 0, 0, 0, 0);\n" +
			"INSERT INTO STATISTICS (ID, AB, H, R, RBI, \"1B\", \"2B\", \"3B\", HR) VALUES (7, 6, 3, 1, 0, 1, 0, 0, 0);\n" +
			"INSERT INTO STATISTICS (ID, AB, H, R, RBI, \"1B\", \"2B\", \"3B\", HR) VALUES (8, 6, 3, 0, 0, 0, 1, 0, 0);\n" +
			"INSERT INTO STATISTICS (ID, AB, H, R, RBI, \"1B\", \"2B\", \"3B\", HR) VALUES (9, 6, 5, 0, 0, 0, 0, 0, 0);\n" +
			"\n" +
			"INSERT INTO STATISTICS (ID, AB, H, R, RBI, \"1B\", \"2B\", \"3B\", HR) VALUES (10, 7, 2, 0, 0, 0, 0, 0, 0);\n" +
			"INSERT INTO STATISTICS (ID, AB, H, R, RBI, \"1B\", \"2B\", \"3B\", HR) VALUES (11, 7, 3, 0, 0, 0, 0, 0, 0);\n" +
			"INSERT INTO STATISTICS (ID, AB, H, R, RBI, \"1B\", \"2B\", \"3B\", HR) VALUES (12, 6, 2, 0, 0, 0, 0, 0, 0);\n" +
			"INSERT INTO STATISTICS (ID, AB, H, R, RBI, \"1B\", \"2B\", \"3B\", HR) VALUES (13, 6, 1, 0, 0, 1, 0, 0, 0);\n" +
			"INSERT INTO STATISTICS (ID, AB, H, R, RBI, \"1B\", \"2B\", \"3B\", HR) VALUES (14, 6, 3, 0, 0, 0, 0, 0, 0);\n" +
			"INSERT INTO STATISTICS (ID, AB, H, R, RBI, \"1B\", \"2B\", \"3B\", HR) VALUES (15, 6, 2, 0, 0, 0, 0, 0, 0);\n" +
			"INSERT INTO STATISTICS (ID, AB, H, R, RBI, \"1B\", \"2B\", \"3B\", HR) VALUES (16, 6, 1, 0, 0, 0, 0, 0, 0);\n" +
			"INSERT INTO STATISTICS (ID, AB, H, R, RBI, \"1B\", \"2B\", \"3B\", HR) VALUES (17, 6, 2, 1, 1, 1, 0, 0, 0);\n" +
			"INSERT INTO STATISTICS (ID, AB, H, R, RBI, \"1B\", \"2B\", \"3B\", HR) VALUES (18, 6, 2, 0, 0, 0, 0, 0, 0);\n" +
			"INSERT INTO STATISTICS (ID, AB, H, R, RBI, \"1B\", \"2B\", \"3B\", HR) VALUES (19, 6, 3, 1, 0, 0, 0, 0, 0);\n" +
			"\n" +
			"INSERT INTO PERFORMED_IN (PLAYER_ID, GAME_ID, STATISTIC_ID) VALUES (0, 1, 0);\n" +
			"INSERT INTO PERFORMED_IN (PLAYER_ID, GAME_ID, STATISTIC_ID) VALUES (1, 1, 1);\n" +
			"INSERT INTO PERFORMED_IN (PLAYER_ID, GAME_ID, STATISTIC_ID) VALUES (2, 1, 2);\n" +
			"INSERT INTO PERFORMED_IN (PLAYER_ID, GAME_ID, STATISTIC_ID) VALUES (3, 1, 3);\n" +
			"INSERT INTO PERFORMED_IN (PLAYER_ID, GAME_ID, STATISTIC_ID) VALUES (4, 1, 4);\n" +
			"INSERT INTO PERFORMED_IN (PLAYER_ID, GAME_ID, STATISTIC_ID) VALUES (5, 1, 5);\n" +
			"INSERT INTO PERFORMED_IN (PLAYER_ID, GAME_ID, STATISTIC_ID) VALUES (6, 1, 6);\n" +
			"INSERT INTO PERFORMED_IN (PLAYER_ID, GAME_ID, STATISTIC_ID) VALUES (7, 1, 7);\n" +
			"INSERT INTO PERFORMED_IN (PLAYER_ID, GAME_ID, STATISTIC_ID) VALUES (8, 1, 8);\n" +
			"INSERT INTO PERFORMED_IN (PLAYER_ID, GAME_ID, STATISTIC_ID) VALUES (9, 1, 9);\n" +
			"\n" +
			"INSERT INTO PERFORMED_IN (PLAYER_ID, GAME_ID, STATISTIC_ID) VALUES (10, 1, 10);\n" +
			"INSERT INTO PERFORMED_IN (PLAYER_ID, GAME_ID, STATISTIC_ID) VALUES (11, 1, 11);\n" +
			"INSERT INTO PERFORMED_IN (PLAYER_ID, GAME_ID, STATISTIC_ID) VALUES (12, 1, 12);\n" +
			"INSERT INTO PERFORMED_IN (PLAYER_ID, GAME_ID, STATISTIC_ID) VALUES (13, 1, 13);\n" +
			"INSERT INTO PERFORMED_IN (PLAYER_ID, GAME_ID, STATISTIC_ID) VALUES (14, 1, 14);\n" +
			"INSERT INTO PERFORMED_IN (PLAYER_ID, GAME_ID, STATISTIC_ID) VALUES (15, 1, 15);\n" +
			"INSERT INTO PERFORMED_IN (PLAYER_ID, GAME_ID, STATISTIC_ID) VALUES (16, 1, 16);\n" +
			"INSERT INTO PERFORMED_IN (PLAYER_ID, GAME_ID, STATISTIC_ID) VALUES (17, 1, 17);\n" +
			"INSERT INTO PERFORMED_IN (PLAYER_ID, GAME_ID, STATISTIC_ID) VALUES (18, 1, 18);\n" +
			"INSERT INTO PERFORMED_IN (PLAYER_ID, GAME_ID, STATISTIC_ID) VALUES (19, 1, 19);\n" +
			"\n" +
			"--game 2\n" +
			"-- INSERT INTO STATISTICS (PLAYER_ID, GAME_ID, AB, H, R, RBI, \"1B\", \"2B\", \"3B\", HR) VALUES\n" +
			"INSERT INTO STATISTICS (ID, AB, H, R, RBI, \"1B\", \"2B\", \"3B\", HR) VALUES (20, 7, 5, 1, 1, 0, 0, 0, 1);\n" +
			"INSERT INTO STATISTICS (ID, AB, H, R, RBI, \"1B\", \"2B\", \"3B\", HR) VALUES (21, 7, 5, 0, 0, 0, 0, 0, 0);\n" +
			"INSERT INTO STATISTICS (ID, AB, H, R, RBI, \"1B\", \"2B\", \"3B\", HR) VALUES (22, 7, 5, 1, 0, 1, 0, 0, 0);\n" +
			"INSERT INTO STATISTICS (ID, AB, H, R, RBI, \"1B\", \"2B\", \"3B\", HR) VALUES (23, 7, 5, 0, 0, 0, 0, 0, 0);\n" +
			"INSERT INTO STATISTICS (ID, AB, H, R, RBI, \"1B\", \"2B\", \"3B\", HR) VALUES (24, 6, 5, 1, 0, 1, 0, 0, 1);\n" +
			"INSERT INTO STATISTICS (ID, AB, H, R, RBI, \"1B\", \"2B\", \"3B\", HR) VALUES (25, 6, 5, 0, 0, 1, 0, 0, 0);\n" +
			"INSERT INTO STATISTICS (ID, AB, H, R, RBI, \"1B\", \"2B\", \"3B\", HR) VALUES (26, 6, 5, 0, 0, 0, 0, 0, 0);\n" +
			"INSERT INTO STATISTICS (ID, AB, H, R, RBI, \"1B\", \"2B\", \"3B\", HR) VALUES (27, 6, 5, 0, 0, 0, 0, 0, 0);\n" +
			"INSERT INTO STATISTICS (ID, AB, H, R, RBI, \"1B\", \"2B\", \"3B\", HR) VALUES (28, 6, 5, 0, 0, 0, 0, 0, 0);\n" +
			"INSERT INTO STATISTICS (ID, AB, H, R, RBI, \"1B\", \"2B\", \"3B\", HR) VALUES (29, 6, 5, 0, 0, 1, 0, 0, 0);\n" +
			"\n" +
			"INSERT INTO STATISTICS (ID, AB, H, R, RBI, \"1B\", \"2B\", \"3B\", HR) VALUES (30, 7, 1, 1, 1, 0, 1, 0, 0);\n" +
			"INSERT INTO STATISTICS (ID, AB, H, R, RBI, \"1B\", \"2B\", \"3B\", HR) VALUES (31, 7, 1, 0, 0, 0, 0, 0, 0);\n" +
			"INSERT INTO STATISTICS (ID, AB, H, R, RBI, \"1B\", \"2B\", \"3B\", HR) VALUES (32, 6, 2, 0, 0, 0, 0, 0, 0);\n" +
			"INSERT INTO STATISTICS (ID, AB, H, R, RBI, \"1B\", \"2B\", \"3B\", HR) VALUES (33, 6, 4, 0, 0, 0, 0, 0, 0);\n" +
			"INSERT INTO STATISTICS (ID, AB, H, R, RBI, \"1B\", \"2B\", \"3B\", HR) VALUES (34, 6, 2, 2, 1, 0, 0, 1, 1);\n" +
			"INSERT INTO STATISTICS (ID, AB, H, R, RBI, \"1B\", \"2B\", \"3B\", HR) VALUES (35, 6, 3, 0, 0, 0, 0, 0, 0);\n" +
			"INSERT INTO STATISTICS (ID, AB, H, R, RBI, \"1B\", \"2B\", \"3B\", HR) VALUES (36, 6, 2, 0, 0, 0, 0, 0, 0);\n" +
			"INSERT INTO STATISTICS (ID, AB, H, R, RBI, \"1B\", \"2B\", \"3B\", HR) VALUES (37, 6, 1, 0, 0, 1, 0, 0, 0);\n" +
			"INSERT INTO STATISTICS (ID, AB, H, R, RBI, \"1B\", \"2B\", \"3B\", HR) VALUES (38, 6, 1, 0, 0, 1, 0, 0, 0);\n" +
			"INSERT INTO STATISTICS (ID, AB, H, R, RBI, \"1B\", \"2B\", \"3B\", HR) VALUES (39, 6, 1, 0, 1, 0, 0, 0, 0);\n" +
			"\n" +
			"INSERT INTO PERFORMED_IN (PLAYER_ID, GAME_ID, STATISTIC_ID) VALUES (0, 2, 20);\n" +
			"INSERT INTO PERFORMED_IN (PLAYER_ID, GAME_ID, STATISTIC_ID) VALUES (1, 2, 21);\n" +
			"INSERT INTO PERFORMED_IN (PLAYER_ID, GAME_ID, STATISTIC_ID) VALUES (2, 2, 22);\n" +
			"INSERT INTO PERFORMED_IN (PLAYER_ID, GAME_ID, STATISTIC_ID) VALUES (3, 2, 23);\n" +
			"INSERT INTO PERFORMED_IN (PLAYER_ID, GAME_ID, STATISTIC_ID) VALUES (4, 2, 24);\n" +
			"INSERT INTO PERFORMED_IN (PLAYER_ID, GAME_ID, STATISTIC_ID) VALUES (5, 2, 25);\n" +
			"INSERT INTO PERFORMED_IN (PLAYER_ID, GAME_ID, STATISTIC_ID) VALUES (6, 2, 26);\n" +
			"INSERT INTO PERFORMED_IN (PLAYER_ID, GAME_ID, STATISTIC_ID) VALUES (7, 2, 27);\n" +
			"INSERT INTO PERFORMED_IN (PLAYER_ID, GAME_ID, STATISTIC_ID) VALUES (8, 2, 28);\n" +
			"INSERT INTO PERFORMED_IN (PLAYER_ID, GAME_ID, STATISTIC_ID) VALUES (9, 2, 29);\n" +
			"\n" +
			"INSERT INTO PERFORMED_IN (PLAYER_ID, GAME_ID, STATISTIC_ID) VALUES (10, 2, 30);\n" +
			"INSERT INTO PERFORMED_IN (PLAYER_ID, GAME_ID, STATISTIC_ID) VALUES (11, 2, 31);\n" +
			"INSERT INTO PERFORMED_IN (PLAYER_ID, GAME_ID, STATISTIC_ID) VALUES (12, 2, 32);\n" +
			"INSERT INTO PERFORMED_IN (PLAYER_ID, GAME_ID, STATISTIC_ID) VALUES (13, 2, 33);\n" +
			"INSERT INTO PERFORMED_IN (PLAYER_ID, GAME_ID, STATISTIC_ID) VALUES (14, 2, 34);\n" +
			"INSERT INTO PERFORMED_IN (PLAYER_ID, GAME_ID, STATISTIC_ID) VALUES (15, 2, 35);\n" +
			"INSERT INTO PERFORMED_IN (PLAYER_ID, GAME_ID, STATISTIC_ID) VALUES (16, 2, 36);\n" +
			"INSERT INTO PERFORMED_IN (PLAYER_ID, GAME_ID, STATISTIC_ID) VALUES (17, 2, 37);\n" +
			"INSERT INTO PERFORMED_IN (PLAYER_ID, GAME_ID, STATISTIC_ID) VALUES (18, 2, 38);\n" +
			"INSERT INTO PERFORMED_IN (PLAYER_ID, GAME_ID, STATISTIC_ID) VALUES (19, 2, 39);\n" +
			"\n" +
			"--game 3\n" +
			"-- INSERT INTO STATISTICS (PLAYER_ID, GAME_ID, AB, H, R, RBI, \"1B\", \"2B\", \"3B\", HR) VALUES\n" +
			"INSERT INTO STATISTICS (ID, AB, H, R, RBI, \"1B\", \"2B\", \"3B\", HR) VALUES (40, 7, 1, 1, 1, 0, 0, 1, 1);\n" +
			"INSERT INTO STATISTICS (ID, AB, H, R, RBI, \"1B\", \"2B\", \"3B\", HR) VALUES (41, 7, 1, 0, 0, 0, 0, 0, 0);\n" +
			"INSERT INTO STATISTICS (ID, AB, H, R, RBI, \"1B\", \"2B\", \"3B\", HR) VALUES (42, 7, 2, 0, 0, 0, 0, 0, 0);\n" +
			"INSERT INTO STATISTICS (ID, AB, H, R, RBI, \"1B\", \"2B\", \"3B\", HR) VALUES (43, 7, 3, 1, 0, 0, 0, 0, 0);\n" +
			"INSERT INTO STATISTICS (ID, AB, H, R, RBI, \"1B\", \"2B\", \"3B\", HR) VALUES (44, 6, 4, 0, 0, 0, 0, 0, 0);\n" +
			"INSERT INTO STATISTICS (ID, AB, H, R, RBI, \"1B\", \"2B\", \"3B\", HR) VALUES (45, 6, 2, 0, 2, 0, 0, 0, 1);\n" +
			"INSERT INTO STATISTICS (ID, AB, H, R, RBI, \"1B\", \"2B\", \"3B\", HR) VALUES (46, 6, 2, 0, 2, 0, 0, 0, 0);\n" +
			"INSERT INTO STATISTICS (ID, AB, H, R, RBI, \"1B\", \"2B\", \"3B\", HR) VALUES (47, 6, 2, 0, 2, 0, 0, 0, 0);\n" +
			"INSERT INTO STATISTICS (ID, AB, H, R, RBI, \"1B\", \"2B\", \"3B\", HR) VALUES (48, 6, 4, 0, 0, 0, 0, 0, 0);\n" +
			"INSERT INTO STATISTICS (ID, AB, H, R, RBI, \"1B\", \"2B\", \"3B\", HR) VALUES (49, 6, 2, 0, 0, 0, 0, 0, 0);\n" +
			"\n" +
			"INSERT INTO STATISTICS (ID, AB, H, R, RBI, \"1B\", \"2B\", \"3B\", HR) VALUES (50, 7, 3, 0, 0, 0, 0, 0, 0);\n" +
			"INSERT INTO STATISTICS (ID, AB, H, R, RBI, \"1B\", \"2B\", \"3B\", HR) VALUES (51, 7, 3, 1, 1, 0, 0, 0, 1);\n" +
			"INSERT INTO STATISTICS (ID, AB, H, R, RBI, \"1B\", \"2B\", \"3B\", HR) VALUES (52, 6, 3, 0, 0, 0, 0, 0, 0);\n" +
			"INSERT INTO STATISTICS (ID, AB, H, R, RBI, \"1B\", \"2B\", \"3B\", HR) VALUES (53, 6, 3, 0, 0, 0, 0, 0, 0);\n" +
			"INSERT INTO STATISTICS (ID, AB, H, R, RBI, \"1B\", \"2B\", \"3B\", HR) VALUES (54, 6, 3, 0, 0, 0, 0, 0, 0);\n" +
			"INSERT INTO STATISTICS (ID, AB, H, R, RBI, \"1B\", \"2B\", \"3B\", HR) VALUES (55, 6, 3, 0, 0, 0, 0, 0, 0);\n" +
			"INSERT INTO STATISTICS (ID, AB, H, R, RBI, \"1B\", \"2B\", \"3B\", HR) VALUES (56, 6, 3, 1, 0, 1, 0, 0, 0);\n" +
			"INSERT INTO STATISTICS (ID, AB, H, R, RBI, \"1B\", \"2B\", \"3B\", HR) VALUES (57, 6, 3, 0, 0, 0, 0, 0, 0);\n" +
			"INSERT INTO STATISTICS (ID, AB, H, R, RBI, \"1B\", \"2B\", \"3B\", HR) VALUES (58, 6, 3, 0, 0, 0, 0, 0, 0);\n" +
			"INSERT INTO STATISTICS (ID, AB, H, R, RBI, \"1B\", \"2B\", \"3B\", HR) VALUES (59, 6, 3, 0, 0, 0, 0, 0, 0);\n" +
			"\n" +
			"INSERT INTO PERFORMED_IN (PLAYER_ID, GAME_ID, STATISTIC_ID) VALUES (0, 3, 30);\n" +
			"INSERT INTO PERFORMED_IN (PLAYER_ID, GAME_ID, STATISTIC_ID) VALUES (1, 3, 31);\n" +
			"INSERT INTO PERFORMED_IN (PLAYER_ID, GAME_ID, STATISTIC_ID) VALUES (2, 3, 32);\n" +
			"INSERT INTO PERFORMED_IN (PLAYER_ID, GAME_ID, STATISTIC_ID) VALUES (3, 3, 33);\n" +
			"INSERT INTO PERFORMED_IN (PLAYER_ID, GAME_ID, STATISTIC_ID) VALUES (4, 3, 34);\n" +
			"INSERT INTO PERFORMED_IN (PLAYER_ID, GAME_ID, STATISTIC_ID) VALUES (5, 3, 35);\n" +
			"INSERT INTO PERFORMED_IN (PLAYER_ID, GAME_ID, STATISTIC_ID) VALUES (6, 3, 36);\n" +
			"INSERT INTO PERFORMED_IN (PLAYER_ID, GAME_ID, STATISTIC_ID) VALUES (7, 3, 37);\n" +
			"INSERT INTO PERFORMED_IN (PLAYER_ID, GAME_ID, STATISTIC_ID) VALUES (8, 3, 38);\n" +
			"INSERT INTO PERFORMED_IN (PLAYER_ID, GAME_ID, STATISTIC_ID) VALUES (9, 3, 39);\n" +
			"\n" +
			"INSERT INTO PERFORMED_IN (PLAYER_ID, GAME_ID, STATISTIC_ID) VALUES (10, 3, 40);\n" +
			"INSERT INTO PERFORMED_IN (PLAYER_ID, GAME_ID, STATISTIC_ID) VALUES (11, 3, 41);\n" +
			"INSERT INTO PERFORMED_IN (PLAYER_ID, GAME_ID, STATISTIC_ID) VALUES (12, 3, 42);\n" +
			"INSERT INTO PERFORMED_IN (PLAYER_ID, GAME_ID, STATISTIC_ID) VALUES (13, 3, 43);\n" +
			"INSERT INTO PERFORMED_IN (PLAYER_ID, GAME_ID, STATISTIC_ID) VALUES (14, 3, 44);\n" +
			"INSERT INTO PERFORMED_IN (PLAYER_ID, GAME_ID, STATISTIC_ID) VALUES (15, 3, 45);\n" +
			"INSERT INTO PERFORMED_IN (PLAYER_ID, GAME_ID, STATISTIC_ID) VALUES (16, 3, 46);\n" +
			"INSERT INTO PERFORMED_IN (PLAYER_ID, GAME_ID, STATISTIC_ID) VALUES (17, 3, 47);\n" +
			"INSERT INTO PERFORMED_IN (PLAYER_ID, GAME_ID, STATISTIC_ID) VALUES (18, 3, 48);\n" +
			"INSERT INTO PERFORMED_IN (PLAYER_ID, GAME_ID, STATISTIC_ID) VALUES (19, 3, 49);\n" +
			"\n" +
			"--game 4\n" +
			"-- INSERT INTO STATISTICS (PLAYER_ID, GAME_ID, AB, H, R, RBI, \"1B\", \"2B\", \"3B\", HR) VALUES\n" +
			"INSERT INTO STATISTICS (ID, AB, H, R, RBI, \"1B\", \"2B\", \"3B\", HR) VALUES (60, 7, 4, 0, 0, 0, 0, 0, 0);\n" +
			"INSERT INTO STATISTICS (ID, AB, H, R, RBI, \"1B\", \"2B\", \"3B\", HR) VALUES (61, 7, 4, 0, 0, 0, 0, 0, 0);\n" +
			"INSERT INTO STATISTICS (ID, AB, H, R, RBI, \"1B\", \"2B\", \"3B\", HR) VALUES (62, 7, 4, 0, 0, 0, 0, 0, 0);\n" +
			"INSERT INTO STATISTICS (ID, AB, H, R, RBI, \"1B\", \"2B\", \"3B\", HR) VALUES (63, 7, 4, 1, 1, 0, 0, 1, 0);\n" +
			"INSERT INTO STATISTICS (ID, AB, H, R, RBI, \"1B\", \"2B\", \"3B\", HR) VALUES (64, 6, 4, 0, 0, 0, 0, 0, 0);\n" +
			"INSERT INTO STATISTICS (ID, AB, H, R, RBI, \"1B\", \"2B\", \"3B\", HR) VALUES (65, 6, 4, 1, 0, 1, 0, 0, 0);\n" +
			"INSERT INTO STATISTICS (ID, AB, H, R, RBI, \"1B\", \"2B\", \"3B\", HR) VALUES (66, 6, 4, 0, 1, 1, 0, 0, 0);\n" +
			"INSERT INTO STATISTICS (ID, AB, H, R, RBI, \"1B\", \"2B\", \"3B\", HR) VALUES (67, 6, 4, 0, 0, 0, 0, 0, 0);\n" +
			"INSERT INTO STATISTICS (ID, AB, H, R, RBI, \"1B\", \"2B\", \"3B\", HR) VALUES (68, 6, 4, 0, 0, 0, 0, 0, 0);\n" +
			"INSERT INTO STATISTICS (ID, AB, H, R, RBI, \"1B\", \"2B\", \"3B\", HR) VALUES (69, 6, 4, 0, 0, 0, 0, 0, 0);\n" +
			"\n" +
			"INSERT INTO STATISTICS (ID, AB, H, R, RBI, \"1B\", \"2B\", \"3B\", HR) VALUES (70, 7, 5, 0, 0, 0, 0, 0, 0);\n" +
			"INSERT INTO STATISTICS (ID, AB, H, R, RBI, \"1B\", \"2B\", \"3B\", HR) VALUES (71, 7, 5, 0, 2, 0, 1, 0, 0);\n" +
			"INSERT INTO STATISTICS (ID, AB, H, R, RBI, \"1B\", \"2B\", \"3B\", HR) VALUES (72, 6, 5, 1, 0, 0, 1, 0, 0);\n" +
			"INSERT INTO STATISTICS (ID, AB, H, R, RBI, \"1B\", \"2B\", \"3B\", HR) VALUES (73, 6, 5, 0, 0, 0, 0, 0, 0);\n" +
			"INSERT INTO STATISTICS (ID, AB, H, R, RBI, \"1B\", \"2B\", \"3B\", HR) VALUES (74, 6, 5, 0, 0, 0, 0, 0, 0);\n" +
			"INSERT INTO STATISTICS (ID, AB, H, R, RBI, \"1B\", \"2B\", \"3B\", HR) VALUES (75, 6, 5, 0, 0, 0, 0, 0, 0);\n" +
			"INSERT INTO STATISTICS (ID, AB, H, R, RBI, \"1B\", \"2B\", \"3B\", HR) VALUES (76, 6, 5, 0, 0, 0, 0, 0, 0);\n" +
			"INSERT INTO STATISTICS (ID, AB, H, R, RBI, \"1B\", \"2B\", \"3B\", HR) VALUES (77, 6, 5, 1, 1, 0, 0, 0, 0);\n" +
			"INSERT INTO STATISTICS (ID, AB, H, R, RBI, \"1B\", \"2B\", \"3B\", HR) VALUES (78, 6, 5, 0, 0, 0, 0, 0, 0);\n" +
			"INSERT INTO STATISTICS (ID, AB, H, R, RBI, \"1B\", \"2B\", \"3B\", HR) VALUES (79, 6, 5, 0, 0, 0, 0, 0, 0);\n" +
			"\n" +
			"INSERT INTO PERFORMED_IN (PLAYER_ID, GAME_ID, STATISTIC_ID) VALUES (0, 4, 60);\n" +
			"INSERT INTO PERFORMED_IN (PLAYER_ID, GAME_ID, STATISTIC_ID) VALUES (1, 4, 61);\n" +
			"INSERT INTO PERFORMED_IN (PLAYER_ID, GAME_ID, STATISTIC_ID) VALUES (2, 4, 62);\n" +
			"INSERT INTO PERFORMED_IN (PLAYER_ID, GAME_ID, STATISTIC_ID) VALUES (3, 4, 63);\n" +
			"INSERT INTO PERFORMED_IN (PLAYER_ID, GAME_ID, STATISTIC_ID) VALUES (4, 4, 64);\n" +
			"INSERT INTO PERFORMED_IN (PLAYER_ID, GAME_ID, STATISTIC_ID) VALUES (5, 4, 65);\n" +
			"INSERT INTO PERFORMED_IN (PLAYER_ID, GAME_ID, STATISTIC_ID) VALUES (6, 4, 66);\n" +
			"INSERT INTO PERFORMED_IN (PLAYER_ID, GAME_ID, STATISTIC_ID) VALUES (7, 4, 67);\n" +
			"INSERT INTO PERFORMED_IN (PLAYER_ID, GAME_ID, STATISTIC_ID) VALUES (8, 4, 68);\n" +
			"INSERT INTO PERFORMED_IN (PLAYER_ID, GAME_ID, STATISTIC_ID) VALUES (9, 4, 69);\n" +
			"\n" +
			"INSERT INTO PERFORMED_IN (PLAYER_ID, GAME_ID, STATISTIC_ID) VALUES (10, 4, 70);\n" +
			"INSERT INTO PERFORMED_IN (PLAYER_ID, GAME_ID, STATISTIC_ID) VALUES (11, 4, 71);\n" +
			"INSERT INTO PERFORMED_IN (PLAYER_ID, GAME_ID, STATISTIC_ID) VALUES (12, 4, 72);\n" +
			"INSERT INTO PERFORMED_IN (PLAYER_ID, GAME_ID, STATISTIC_ID) VALUES (13, 4, 73);\n" +
			"INSERT INTO PERFORMED_IN (PLAYER_ID, GAME_ID, STATISTIC_ID) VALUES (14, 4, 74);\n" +
			"INSERT INTO PERFORMED_IN (PLAYER_ID, GAME_ID, STATISTIC_ID) VALUES (15, 4, 75);\n" +
			"INSERT INTO PERFORMED_IN (PLAYER_ID, GAME_ID, STATISTIC_ID) VALUES (16, 4, 76);\n" +
			"INSERT INTO PERFORMED_IN (PLAYER_ID, GAME_ID, STATISTIC_ID) VALUES (17, 4, 77);\n" +
			"INSERT INTO PERFORMED_IN (PLAYER_ID, GAME_ID, STATISTIC_ID) VALUES (18, 4, 78);\n" +
			"INSERT INTO PERFORMED_IN (PLAYER_ID, GAME_ID, STATISTIC_ID) VALUES (19, 4, 79);\n" +
			"\n" +
			"\n" +
			"--season 2\n" +
			"--game 5\n" +
			"INSERT INTO STATISTICS (ID, AB, H, R, RBI, \"1B\", \"2B\", \"3B\", HR) VALUES (80, 5, 4, 1, 3, 0, 0, 0, 1);\n" +
			"INSERT INTO STATISTICS (ID, AB, H, R, RBI, \"1B\", \"2B\", \"3B\", HR) VALUES (81, 5, 4, 0, 0, 0, 0, 0, 0);\n" +
			"INSERT INTO STATISTICS (ID, AB, H, R, RBI, \"1B\", \"2B\", \"3B\", HR) VALUES (82, 5, 4, 0, 0, 0, 0, 0, 0);\n" +
			"INSERT INTO STATISTICS (ID, AB, H, R, RBI, \"1B\", \"2B\", \"3B\", HR) VALUES (83, 5, 4, 1, 1, 1, 0, 0, 0);\n" +
			"INSERT INTO STATISTICS (ID, AB, H, R, RBI, \"1B\", \"2B\", \"3B\", HR) VALUES (84, 5, 4, 1, 1, 1, 0, 0, 0);\n" +
			"INSERT INTO STATISTICS (ID, AB, H, R, RBI, \"1B\", \"2B\", \"3B\", HR) VALUES (85, 5, 4, 1, 1, 0, 1, 0, 0);\n" +
			"INSERT INTO STATISTICS (ID, AB, H, R, RBI, \"1B\", \"2B\", \"3B\", HR) VALUES (86, 5, 4, 1, 1, 2, 0, 0, 0);\n" +
			"INSERT INTO STATISTICS (ID, AB, H, R, RBI, \"1B\", \"2B\", \"3B\", HR) VALUES (87, 5, 4, 2, 1, 1, 0, 0, 0);\n" +
			"INSERT INTO STATISTICS (ID, AB, H, R, RBI, \"1B\", \"2B\", \"3B\", HR) VALUES (88, 5, 4, 1, 0, 1, 0, 0, 0);\n" +
			"INSERT INTO STATISTICS (ID, AB, H, R, RBI, \"1B\", \"2B\", \"3B\", HR) VALUES (89, 5, 4, 1, 0, 0, 1, 0, 0);\n" +
			"\n" +
			"INSERT INTO STATISTICS (ID, AB, H, R, RBI, \"1B\", \"2B\", \"3B\", HR) VALUES (90, 5, 4, 0, 0, 0, 0, 0, 0);\n" +
			"INSERT INTO STATISTICS (ID, AB, H, R, RBI, \"1B\", \"2B\", \"3B\", HR) VALUES (91, 5, 4, 1, 1, 0, 1, 0, 0);\n" +
			"INSERT INTO STATISTICS (ID, AB, H, R, RBI, \"1B\", \"2B\", \"3B\", HR) VALUES (92, 5, 4, 0, 0, 0, 0, 0, 0);\n" +
			"INSERT INTO STATISTICS (ID, AB, H, R, RBI, \"1B\", \"2B\", \"3B\", HR) VALUES (93, 5, 4, 0, 0, 0, 0, 0, 0);\n" +
			"INSERT INTO STATISTICS (ID, AB, H, R, RBI, \"1B\", \"2B\", \"3B\", HR) VALUES (94, 5, 4, 0, 0, 0, 0, 0, 0);\n" +
			"INSERT INTO STATISTICS (ID, AB, H, R, RBI, \"1B\", \"2B\", \"3B\", HR) VALUES (95, 5, 4, 0, 0, 0, 0, 0, 0);\n" +
			"INSERT INTO STATISTICS (ID, AB, H, R, RBI, \"1B\", \"2B\", \"3B\", HR) VALUES (96, 5, 4, 0, 0, 0, 0, 0, 0);\n" +
			"INSERT INTO STATISTICS (ID, AB, H, R, RBI, \"1B\", \"2B\", \"3B\", HR) VALUES (97, 5, 4, 0, 0, 0, 0, 0, 0);\n" +
			"INSERT INTO STATISTICS (ID, AB, H, R, RBI, \"1B\", \"2B\", \"3B\", HR) VALUES (98, 5, 4, 0, 0, 0, 0, 0, 0);\n" +
			"INSERT INTO STATISTICS (ID, AB, H, R, RBI, \"1B\", \"2B\", \"3B\", HR) VALUES (99, 5, 4, 1, 1, 0, 0, 0, 0);\n" +
			"\n" +
			"INSERT INTO PERFORMED_IN (PLAYER_ID, GAME_ID, STATISTIC_ID) VALUES (0, 5, 80);\n" +
			"INSERT INTO PERFORMED_IN (PLAYER_ID, GAME_ID, STATISTIC_ID) VALUES (1, 5, 81);\n" +
			"INSERT INTO PERFORMED_IN (PLAYER_ID, GAME_ID, STATISTIC_ID) VALUES (2, 5, 82);\n" +
			"INSERT INTO PERFORMED_IN (PLAYER_ID, GAME_ID, STATISTIC_ID) VALUES (3, 5, 83);\n" +
			"INSERT INTO PERFORMED_IN (PLAYER_ID, GAME_ID, STATISTIC_ID) VALUES (4, 5, 84);\n" +
			"INSERT INTO PERFORMED_IN (PLAYER_ID, GAME_ID, STATISTIC_ID) VALUES (5, 5, 85);\n" +
			"INSERT INTO PERFORMED_IN (PLAYER_ID, GAME_ID, STATISTIC_ID) VALUES (6, 5, 86);\n" +
			"INSERT INTO PERFORMED_IN (PLAYER_ID, GAME_ID, STATISTIC_ID) VALUES (10, 5, 87);\n" +
			"INSERT INTO PERFORMED_IN (PLAYER_ID, GAME_ID, STATISTIC_ID) VALUES (11, 5, 88);\n" +
			"INSERT INTO PERFORMED_IN (PLAYER_ID, GAME_ID, STATISTIC_ID) VALUES (15, 5, 89);\n" +
			"\n" +
			"INSERT INTO PERFORMED_IN (PLAYER_ID, GAME_ID, STATISTIC_ID) VALUES (7, 5, 90);\n" +
			"INSERT INTO PERFORMED_IN (PLAYER_ID, GAME_ID, STATISTIC_ID) VALUES (8, 5, 91);\n" +
			"INSERT INTO PERFORMED_IN (PLAYER_ID, GAME_ID, STATISTIC_ID) VALUES (9, 5, 92);\n" +
			"INSERT INTO PERFORMED_IN (PLAYER_ID, GAME_ID, STATISTIC_ID) VALUES (12, 5, 93);\n" +
			"INSERT INTO PERFORMED_IN (PLAYER_ID, GAME_ID, STATISTIC_ID) VALUES (13, 5, 94);\n" +
			"INSERT INTO PERFORMED_IN (PLAYER_ID, GAME_ID, STATISTIC_ID) VALUES (14, 5, 95);\n" +
			"INSERT INTO PERFORMED_IN (PLAYER_ID, GAME_ID, STATISTIC_ID) VALUES (17, 5, 96);\n" +
			"INSERT INTO PERFORMED_IN (PLAYER_ID, GAME_ID, STATISTIC_ID) VALUES (18, 5, 97);\n" +
			"INSERT INTO PERFORMED_IN (PLAYER_ID, GAME_ID, STATISTIC_ID) VALUES (19, 5, 98);\n" +
			"INSERT INTO PERFORMED_IN (PLAYER_ID, GAME_ID, STATISTIC_ID) VALUES (20, 5, 99);\n" +
			"\n" +
			"--game 6\n" +
			"INSERT INTO STATISTICS (ID, AB, H, R, RBI, \"1B\", \"2B\", \"3B\", HR) VALUES (100, 6, 4, 0, 0, 0, 0, 0, 0);\n" +
			"INSERT INTO STATISTICS (ID, AB, H, R, RBI, \"1B\", \"2B\", \"3B\", HR) VALUES (101, 6, 4, 0, 0, 0, 0, 0, 0);\n" +
			"INSERT INTO STATISTICS (ID, AB, H, R, RBI, \"1B\", \"2B\", \"3B\", HR) VALUES (102, 6, 4, 0, 1, 0, 1, 0, 0);\n" +
			"INSERT INTO STATISTICS (ID, AB, H, R, RBI, \"1B\", \"2B\", \"3B\", HR) VALUES (103, 6, 4, 0, 0, 0, 0, 0, 0);\n" +
			"INSERT INTO STATISTICS (ID, AB, H, R, RBI, \"1B\", \"2B\", \"3B\", HR) VALUES (104, 6, 4, 0, 0, 0, 0, 0, 0);\n" +
			"INSERT INTO STATISTICS (ID, AB, H, R, RBI, \"1B\", \"2B\", \"3B\", HR) VALUES (105, 6, 4, 1, 1, 0, 1, 0, 0);\n" +
			"INSERT INTO STATISTICS (ID, AB, H, R, RBI, \"1B\", \"2B\", \"3B\", HR) VALUES (106, 6, 4, 0, 0, 0, 0, 0, 0);\n" +
			"INSERT INTO STATISTICS (ID, AB, H, R, RBI, \"1B\", \"2B\", \"3B\", HR) VALUES (107, 6, 4, 0, 0, 1, 0, 0, 0);\n" +
			"INSERT INTO STATISTICS (ID, AB, H, R, RBI, \"1B\", \"2B\", \"3B\", HR) VALUES (108, 6, 4, 0, 0, 0, 0, 0, 0);\n" +
			"INSERT INTO STATISTICS (ID, AB, H, R, RBI, \"1B\", \"2B\", \"3B\", HR) VALUES (109, 6, 4, 0, 0, 0, 0, 0, 0);\n" +
			"\n" +
			"INSERT INTO STATISTICS (ID, AB, H, R, RBI, \"1B\", \"2B\", \"3B\", HR) VALUES (110, 6, 4, 0, 0, 0, 0, 0, 0);\n" +
			"INSERT INTO STATISTICS (ID, AB, H, R, RBI, \"1B\", \"2B\", \"3B\", HR) VALUES (111, 6, 4, 0, 0, 0, 0, 0, 0);\n" +
			"INSERT INTO STATISTICS (ID, AB, H, R, RBI, \"1B\", \"2B\", \"3B\", HR) VALUES (112, 6, 4, 2, 1, 1, 0, 0, 1);\n" +
			"INSERT INTO STATISTICS (ID, AB, H, R, RBI, \"1B\", \"2B\", \"3B\", HR) VALUES (113, 6, 4, 0, 0, 0, 0, 0, 0);\n" +
			"INSERT INTO STATISTICS (ID, AB, H, R, RBI, \"1B\", \"2B\", \"3B\", HR) VALUES (114, 6, 4, 0, 1, 0, 0, 1, 0);\n" +
			"INSERT INTO STATISTICS (ID, AB, H, R, RBI, \"1B\", \"2B\", \"3B\", HR) VALUES (115, 6, 4, 0, 0, 0, 0, 0, 0);\n" +
			"INSERT INTO STATISTICS (ID, AB, H, R, RBI, \"1B\", \"2B\", \"3B\", HR) VALUES (116, 6, 4, 1, 0, 1, 0, 0, 0);\n" +
			"INSERT INTO STATISTICS (ID, AB, H, R, RBI, \"1B\", \"2B\", \"3B\", HR) VALUES (117, 6, 4, 0, 0, 0, 0, 0, 0);\n" +
			"INSERT INTO STATISTICS (ID, AB, H, R, RBI, \"1B\", \"2B\", \"3B\", HR) VALUES (118, 6, 4, 0, 0, 0, 0, 0, 0);\n" +
			"INSERT INTO STATISTICS (ID, AB, H, R, RBI, \"1B\", \"2B\", \"3B\", HR) VALUES (119, 6, 4, 0, 0, 0, 0, 0, 0);\n" +
			"\n" +
			"INSERT INTO PERFORMED_IN (PLAYER_ID, GAME_ID, STATISTIC_ID) VALUES (0, 6, 100);\n" +
			"INSERT INTO PERFORMED_IN (PLAYER_ID, GAME_ID, STATISTIC_ID) VALUES (1, 6, 101);\n" +
			"INSERT INTO PERFORMED_IN (PLAYER_ID, GAME_ID, STATISTIC_ID) VALUES (2, 6, 102);\n" +
			"INSERT INTO PERFORMED_IN (PLAYER_ID, GAME_ID, STATISTIC_ID) VALUES (3, 6, 103);\n" +
			"INSERT INTO PERFORMED_IN (PLAYER_ID, GAME_ID, STATISTIC_ID) VALUES (4, 6, 104);\n" +
			"INSERT INTO PERFORMED_IN (PLAYER_ID, GAME_ID, STATISTIC_ID) VALUES (5, 6, 105);\n" +
			"INSERT INTO PERFORMED_IN (PLAYER_ID, GAME_ID, STATISTIC_ID) VALUES (6, 6, 106);\n" +
			"INSERT INTO PERFORMED_IN (PLAYER_ID, GAME_ID, STATISTIC_ID) VALUES (10, 6, 107);\n" +
			"INSERT INTO PERFORMED_IN (PLAYER_ID, GAME_ID, STATISTIC_ID) VALUES (11, 6, 108);\n" +
			"INSERT INTO PERFORMED_IN (PLAYER_ID, GAME_ID, STATISTIC_ID) VALUES (15, 6, 109);\n" +
			"\n" +
			"INSERT INTO PERFORMED_IN (PLAYER_ID, GAME_ID, STATISTIC_ID) VALUES (7, 6, 110);\n" +
			"INSERT INTO PERFORMED_IN (PLAYER_ID, GAME_ID, STATISTIC_ID) VALUES (8, 6, 111);\n" +
			"INSERT INTO PERFORMED_IN (PLAYER_ID, GAME_ID, STATISTIC_ID) VALUES (9, 6, 112);\n" +
			"INSERT INTO PERFORMED_IN (PLAYER_ID, GAME_ID, STATISTIC_ID) VALUES (12, 6, 113);\n" +
			"INSERT INTO PERFORMED_IN (PLAYER_ID, GAME_ID, STATISTIC_ID) VALUES (13, 6, 114);\n" +
			"INSERT INTO PERFORMED_IN (PLAYER_ID, GAME_ID, STATISTIC_ID) VALUES (14, 6, 115);\n" +
			"INSERT INTO PERFORMED_IN (PLAYER_ID, GAME_ID, STATISTIC_ID) VALUES (17, 6, 116);\n" +
			"INSERT INTO PERFORMED_IN (PLAYER_ID, GAME_ID, STATISTIC_ID) VALUES (18, 6, 117);\n" +
			"INSERT INTO PERFORMED_IN (PLAYER_ID, GAME_ID, STATISTIC_ID) VALUES (19, 6, 118);\n" +
			"INSERT INTO PERFORMED_IN (PLAYER_ID, GAME_ID, STATISTIC_ID) VALUES (20, 6, 119);\n" +
			"\n" +
			"--game 7\n" +
			"INSERT INTO STATISTICS (ID, AB, H, R, RBI, \"1B\", \"2B\", \"3B\", HR) VALUES (120, 7, 4, 0, 0, 0, 0, 0, 0);\n" +
			"INSERT INTO STATISTICS (ID, AB, H, R, RBI, \"1B\", \"2B\", \"3B\", HR) VALUES (121, 7, 4, 0, 0, 0, 0, 0, 0);\n" +
			"INSERT INTO STATISTICS (ID, AB, H, R, RBI, \"1B\", \"2B\", \"3B\", HR) VALUES (122, 7, 4, 1, 0, 0, 0, 0, 1);\n" +
			"INSERT INTO STATISTICS (ID, AB, H, R, RBI, \"1B\", \"2B\", \"3B\", HR) VALUES (123, 7, 4, 0, 0, 0, 0, 0, 0);\n" +
			"INSERT INTO STATISTICS (ID, AB, H, R, RBI, \"1B\", \"2B\", \"3B\", HR) VALUES (124, 7, 4, 0, 0, 0, 0, 0, 0);\n" +
			"INSERT INTO STATISTICS (ID, AB, H, R, RBI, \"1B\", \"2B\", \"3B\", HR) VALUES (125, 7, 4, 0, 0, 1, 0, 0, 0);\n" +
			"INSERT INTO STATISTICS (ID, AB, H, R, RBI, \"1B\", \"2B\", \"3B\", HR) VALUES (126, 7, 4, 0, 0, 0, 0, 0, 0);\n" +
			"INSERT INTO STATISTICS (ID, AB, H, R, RBI, \"1B\", \"2B\", \"3B\", HR) VALUES (127, 7, 4, 0, 0, 0, 1, 0, 0);\n" +
			"INSERT INTO STATISTICS (ID, AB, H, R, RBI, \"1B\", \"2B\", \"3B\", HR) VALUES (128, 7, 4, 0, 1, 0, 0, 1, 0);\n" +
			"INSERT INTO STATISTICS (ID, AB, H, R, RBI, \"1B\", \"2B\", \"3B\", HR) VALUES (129, 7, 4, 1, 0, 0, 0, 0, 0);\n" +
			"\n" +
			"INSERT INTO STATISTICS (ID, AB, H, R, RBI, \"1B\", \"2B\", \"3B\", HR) VALUES (130, 7, 4, 0, 0, 0, 0, 0, 0);\n" +
			"INSERT INTO STATISTICS (ID, AB, H, R, RBI, \"1B\", \"2B\", \"3B\", HR) VALUES (131, 7, 4, 0, 1, 0, 0, 1, 0);\n" +
			"INSERT INTO STATISTICS (ID, AB, H, R, RBI, \"1B\", \"2B\", \"3B\", HR) VALUES (132, 7, 4, 0, 0, 0, 0, 0, 0);\n" +
			"INSERT INTO STATISTICS (ID, AB, H, R, RBI, \"1B\", \"2B\", \"3B\", HR) VALUES (133, 7, 4, 0, 0, 0, 0, 0, 0);\n" +
			"INSERT INTO STATISTICS (ID, AB, H, R, RBI, \"1B\", \"2B\", \"3B\", HR) VALUES (134, 7, 4, 1, 2, 0, 0, 0, 1);\n" +
			"INSERT INTO STATISTICS (ID, AB, H, R, RBI, \"1B\", \"2B\", \"3B\", HR) VALUES (135, 7, 4, 0, 0, 0, 0, 0, 0);\n" +
			"INSERT INTO STATISTICS (ID, AB, H, R, RBI, \"1B\", \"2B\", \"3B\", HR) VALUES (136, 7, 4, 0, 0, 0, 0, 0, 0);\n" +
			"INSERT INTO STATISTICS (ID, AB, H, R, RBI, \"1B\", \"2B\", \"3B\", HR) VALUES (137, 7, 4, 2, 1, 1, 0, 1, 0);\n" +
			"INSERT INTO STATISTICS (ID, AB, H, R, RBI, \"1B\", \"2B\", \"3B\", HR) VALUES (138, 7, 4, 0, 0, 0, 0, 0, 0);\n" +
			"INSERT INTO STATISTICS (ID, AB, H, R, RBI, \"1B\", \"2B\", \"3B\", HR) VALUES (139, 7, 4, 1, 0, 1, 0, 0, 0);\n" +
			"\n" +
			"INSERT INTO PERFORMED_IN (PLAYER_ID, GAME_ID, STATISTIC_ID) VALUES (0, 7, 120);\n" +
			"INSERT INTO PERFORMED_IN (PLAYER_ID, GAME_ID, STATISTIC_ID) VALUES (1, 7, 121);\n" +
			"INSERT INTO PERFORMED_IN (PLAYER_ID, GAME_ID, STATISTIC_ID) VALUES (2, 7, 122);\n" +
			"INSERT INTO PERFORMED_IN (PLAYER_ID, GAME_ID, STATISTIC_ID) VALUES (3, 7, 123);\n" +
			"INSERT INTO PERFORMED_IN (PLAYER_ID, GAME_ID, STATISTIC_ID) VALUES (4, 7, 124);\n" +
			"INSERT INTO PERFORMED_IN (PLAYER_ID, GAME_ID, STATISTIC_ID) VALUES (5, 7, 125);\n" +
			"INSERT INTO PERFORMED_IN (PLAYER_ID, GAME_ID, STATISTIC_ID) VALUES (6, 7, 126);\n" +
			"INSERT INTO PERFORMED_IN (PLAYER_ID, GAME_ID, STATISTIC_ID) VALUES (10, 7, 127);\n" +
			"INSERT INTO PERFORMED_IN (PLAYER_ID, GAME_ID, STATISTIC_ID) VALUES (11, 7, 128);\n" +
			"INSERT INTO PERFORMED_IN (PLAYER_ID, GAME_ID, STATISTIC_ID) VALUES (15, 7, 129);\n" +
			"\n" +
			"INSERT INTO PERFORMED_IN (PLAYER_ID, GAME_ID, STATISTIC_ID) VALUES (7, 7, 130);\n" +
			"INSERT INTO PERFORMED_IN (PLAYER_ID, GAME_ID, STATISTIC_ID) VALUES (8, 7, 131);\n" +
			"INSERT INTO PERFORMED_IN (PLAYER_ID, GAME_ID, STATISTIC_ID) VALUES (9, 7, 132);\n" +
			"INSERT INTO PERFORMED_IN (PLAYER_ID, GAME_ID, STATISTIC_ID) VALUES (12, 7, 133);\n" +
			"INSERT INTO PERFORMED_IN (PLAYER_ID, GAME_ID, STATISTIC_ID) VALUES (13, 7, 134);\n" +
			"INSERT INTO PERFORMED_IN (PLAYER_ID, GAME_ID, STATISTIC_ID) VALUES (14, 7, 135);\n" +
			"INSERT INTO PERFORMED_IN (PLAYER_ID, GAME_ID, STATISTIC_ID) VALUES (17, 7, 136);\n" +
			"INSERT INTO PERFORMED_IN (PLAYER_ID, GAME_ID, STATISTIC_ID) VALUES (18, 7, 137);\n" +
			"INSERT INTO PERFORMED_IN (PLAYER_ID, GAME_ID, STATISTIC_ID) VALUES (19, 7, 138);\n" +
			"INSERT INTO PERFORMED_IN (PLAYER_ID, GAME_ID, STATISTIC_ID) VALUES (20, 7, 139);\n" +
			"\n" +
			"--game 8\n" +
			"INSERT INTO STATISTICS (ID, AB, H, R, RBI, \"1B\", \"2B\", \"3B\", HR) VALUES (140, 5, 4, 0, 0, 0, 0, 0, 0);\n" +
			"INSERT INTO STATISTICS (ID, AB, H, R, RBI, \"1B\", \"2B\", \"3B\", HR) VALUES (141, 5, 4, 0, 0, 0, 0, 0, 0);\n" +
			"INSERT INTO STATISTICS (ID, AB, H, R, RBI, \"1B\", \"2B\", \"3B\", HR) VALUES (142, 5, 4, 0, 0, 0, 0, 0, 0);\n" +
			"INSERT INTO STATISTICS (ID, AB, H, R, RBI, \"1B\", \"2B\", \"3B\", HR) VALUES (143, 5, 4, 0, 0, 0, 0, 0, 0);\n" +
			"INSERT INTO STATISTICS (ID, AB, H, R, RBI, \"1B\", \"2B\", \"3B\", HR) VALUES (144, 5, 4, 1, 1, 0, 1, 0, 0);\n" +
			"INSERT INTO STATISTICS (ID, AB, H, R, RBI, \"1B\", \"2B\", \"3B\", HR) VALUES (145, 5, 4, 0, 0, 0, 0, 0, 0);\n" +
			"INSERT INTO STATISTICS (ID, AB, H, R, RBI, \"1B\", \"2B\", \"3B\", HR) VALUES (146, 5, 4, 1, 0, 0, 0, 1, 0);\n" +
			"INSERT INTO STATISTICS (ID, AB, H, R, RBI, \"1B\", \"2B\", \"3B\", HR) VALUES (147, 5, 4, 0, 0, 0, 0, 0, 0);\n" +
			"INSERT INTO STATISTICS (ID, AB, H, R, RBI, \"1B\", \"2B\", \"3B\", HR) VALUES (148, 5, 4, 0, 1, 0, 0, 1, 0);\n" +
			"INSERT INTO STATISTICS (ID, AB, H, R, RBI, \"1B\", \"2B\", \"3B\", HR) VALUES (149, 5, 4, 0, 0, 0, 0, 0, 0);\n" +
			"\n" +
			"INSERT INTO STATISTICS (ID, AB, H, R, RBI, \"1B\", \"2B\", \"3B\", HR) VALUES (150, 5, 4, 1, 0, 0, 0, 0, 1);\n" +
			"INSERT INTO STATISTICS (ID, AB, H, R, RBI, \"1B\", \"2B\", \"3B\", HR) VALUES (151, 5, 4, 0, 0, 0, 0, 0, 0);\n" +
			"INSERT INTO STATISTICS (ID, AB, H, R, RBI, \"1B\", \"2B\", \"3B\", HR) VALUES (152, 5, 4, 0, 0, 0, 0, 0, 0);\n" +
			"INSERT INTO STATISTICS (ID, AB, H, R, RBI, \"1B\", \"2B\", \"3B\", HR) VALUES (153, 5, 4, 2, 1, 0, 1, 1, 0);\n" +
			"INSERT INTO STATISTICS (ID, AB, H, R, RBI, \"1B\", \"2B\", \"3B\", HR) VALUES (154, 5, 4, 0, 0, 0, 0, 0, 0);\n" +
			"INSERT INTO STATISTICS (ID, AB, H, R, RBI, \"1B\", \"2B\", \"3B\", HR) VALUES (155, 5, 4, 0, 0, 0, 0, 0, 0);\n" +
			"INSERT INTO STATISTICS (ID, AB, H, R, RBI, \"1B\", \"2B\", \"3B\", HR) VALUES (156, 5, 4, 1, 1, 1, 0, 0, 0);\n" +
			"INSERT INTO STATISTICS (ID, AB, H, R, RBI, \"1B\", \"2B\", \"3B\", HR) VALUES (157, 5, 4, 0, 0, 0, 0, 0, 0);\n" +
			"INSERT INTO STATISTICS (ID, AB, H, R, RBI, \"1B\", \"2B\", \"3B\", HR) VALUES (158, 5, 4, 1, 2, 0, 1, 0, 0);\n" +
			"INSERT INTO STATISTICS (ID, AB, H, R, RBI, \"1B\", \"2B\", \"3B\", HR) VALUES (159, 5, 4, 0, 0, 0, 0, 0, 0);\n" +
			"\n" +
			"INSERT INTO PERFORMED_IN (PLAYER_ID, GAME_ID, STATISTIC_ID) VALUES (0, 8, 140);\n" +
			"INSERT INTO PERFORMED_IN (PLAYER_ID, GAME_ID, STATISTIC_ID) VALUES (1, 8, 141);\n" +
			"INSERT INTO PERFORMED_IN (PLAYER_ID, GAME_ID, STATISTIC_ID) VALUES (2, 8, 142);\n" +
			"INSERT INTO PERFORMED_IN (PLAYER_ID, GAME_ID, STATISTIC_ID) VALUES (3, 8, 143);\n" +
			"INSERT INTO PERFORMED_IN (PLAYER_ID, GAME_ID, STATISTIC_ID) VALUES (4, 8, 144);\n" +
			"INSERT INTO PERFORMED_IN (PLAYER_ID, GAME_ID, STATISTIC_ID) VALUES (5, 8, 145);\n" +
			"INSERT INTO PERFORMED_IN (PLAYER_ID, GAME_ID, STATISTIC_ID) VALUES (6, 8, 146);\n" +
			"INSERT INTO PERFORMED_IN (PLAYER_ID, GAME_ID, STATISTIC_ID) VALUES (10, 8, 147);\n" +
			"INSERT INTO PERFORMED_IN (PLAYER_ID, GAME_ID, STATISTIC_ID) VALUES (11, 8, 148);\n" +
			"INSERT INTO PERFORMED_IN (PLAYER_ID, GAME_ID, STATISTIC_ID) VALUES (15, 8, 149);\n" +
			"\n" +
			"INSERT INTO PERFORMED_IN (PLAYER_ID, GAME_ID, STATISTIC_ID) VALUES (7, 8, 150);\n" +
			"INSERT INTO PERFORMED_IN (PLAYER_ID, GAME_ID, STATISTIC_ID) VALUES (8, 8, 151);\n" +
			"INSERT INTO PERFORMED_IN (PLAYER_ID, GAME_ID, STATISTIC_ID) VALUES (9, 8, 152);\n" +
			"INSERT INTO PERFORMED_IN (PLAYER_ID, GAME_ID, STATISTIC_ID) VALUES (12, 8, 153);\n" +
			"INSERT INTO PERFORMED_IN (PLAYER_ID, GAME_ID, STATISTIC_ID) VALUES (13, 8, 154);\n" +
			"INSERT INTO PERFORMED_IN (PLAYER_ID, GAME_ID, STATISTIC_ID) VALUES (14, 8, 155);\n" +
			"INSERT INTO PERFORMED_IN (PLAYER_ID, GAME_ID, STATISTIC_ID) VALUES (17, 8, 156);\n" +
			"INSERT INTO PERFORMED_IN (PLAYER_ID, GAME_ID, STATISTIC_ID) VALUES (18, 8, 157);\n" +
			"INSERT INTO PERFORMED_IN (PLAYER_ID, GAME_ID, STATISTIC_ID) VALUES (19, 8, 158);\n" +
			"INSERT INTO PERFORMED_IN (PLAYER_ID, GAME_ID, STATISTIC_ID) VALUES (20, 8, 159);\n" +
			"\n";

	public static final String C_TABLES =
		"CREATE TABLE MMOHOROV.TEAMS\n" +
			"(\n" +
			"  id INT PRIMARY KEY NOT NULL,\n" +
			"  name VARCHAR(25)\n" +
			");\n" +
			"\n" +
			"\n" +
			"CREATE TABLE MMOHOROV.PLAYERS\n" +
			"(\n" +
			"  id INT PRIMARY KEY NOT NULL,\n" +
			"  first_name VARCHAR(25),\n" +
			"  last_name VARCHAR(25)\n" +
			");\n" +
			"\n" +
			"\n" +
			"CREATE TABLE MMOHOROV.SEASONS\n" +
			"(\n" +
			"  id INT PRIMARY KEY,\n" +
			"  year INT NOT NULL,\n" +
			"  type VARCHAR(10) NOT NULL\n" +
			");\n" +
			"\n" +
			"\n" +
			"CREATE TABLE MMOHOROV.PLAYS_FOR\n" +
			"(\n" +
			"  PLAYER_ID INT,\n" +
			"  SEASON_ID INT,\n" +
			"  TEAM_ID INT,\n" +
			"  CONSTRAINT PLAY PRIMARY KEY (PLAYER_ID, TEAM_ID, SEASON_ID),\n" +
			"  CONSTRAINT PLAYER_ID FOREIGN KEY (PLAYER_ID) REFERENCES PLAYERS (ID),\n" +
			"  CONSTRAINT SEASON_ID FOREIGN KEY (SEASON_ID) REFERENCES SEASONS (ID),\n" +
			"  CONSTRAINT TEAM_ID FOREIGN KEY (TEAM_ID) REFERENCES TEAMS (ID)\n" +
			");\n" +
			"\n" +
			"\n" +
			"CREATE TABLE MMOHOROV.GAMES\n" +
			"(\n" +
			"  ID INT PRIMARY KEY NOT NULL,\n" +
			"  HOME_TEAM_ID INT NOT NULL,\n" +
			"  VISITOR_TEAM_ID INT NOT NULL,\n" +
			"  SEASON_ID INT NOT NULL,\n" +
			"  HOME_SCORE INT NOT NULL,\n" +
			"  VISITOR_SCORE INT NOT NULL,\n" +
			"  GAME_LOCATION VARCHAR2(50) NOT NULL,\n" +
			"  GAME_DATE TIMESTAMP NOT NULL,\n" +
			"  CONSTRAINT HOME_TEAM_ID FOREIGN KEY (HOME_TEAM_ID) REFERENCES TEAMS (ID),\n" +
			"  CONSTRAINT VISITOR_TEAM_ID FOREIGN KEY (VISITOR_TEAM_ID) REFERENCES TEAMS (ID),\n" +
			"  CONSTRAINT GAME_SEASON_ID FOREIGN KEY (SEASON_ID) REFERENCES SEASONS (ID)\n" +
			");\n" +
			"\n" +
			"CREATE TABLE MMOHOROV.STATISTICS\n" +
			"(\n" +
			"  ID INT PRIMARY KEY NOT NULL,\n" +
			"  AB INT NOT NULL,\n" +
			"  H INT NOT NULL,\n" +
			"  R INT NOT NULL,\n" +
			"  RBI INT NOT NULL,\n" +
			"  \"1B\" INT NOT NULL,\n" +
			"  \"2B\" INT NOT NULL,\n" +
			"  \"3B\" INT NOT NULL,\n" +
			"  HR INT NOT NULL\n" +
			");\n" +
			"\n" +
			"\n" +
			"CREATE TABLE MMOHOROV.PERFORMED_IN\n" +
			"(\n" +
			"  PLAYER_ID INT NOT NULL,\n" +
			"  GAME_ID INT NOT NULL,\n" +
			"  STATISTIC_ID INT NOT NULL,\n" +
			"  CONSTRAINT PERFORMED_IN_PERFORMANCE_ID PRIMARY KEY (PLAYER_ID, GAME_ID, STATISTIC_ID),\n" +
			"  CONSTRAINT PERFORMED_IN_PLAYER_ID_S FOREIGN KEY (PLAYER_ID) REFERENCES PLAYERS (ID),\n" +
			"  CONSTRAINT PERFORMED_IN_GAME_ID FOREIGN KEY (GAME_ID) REFERENCES GAMES (ID),\n" +
			"  CONSTRAINT PERFORMED_IN_STATISTIC_ID FOREIGN KEY (STATISTIC_ID) REFERENCES STATISTICS(ID)\n" +
			");\n";

	public static final String D_TABLES =
		"DROP TABLE MMOHOROV.PERFORMED_IN;\n" +
			"DROP TABLE MMOHOROV.STATISTICS;\n" +
			"DROP TABLE MMOHOROV.GAMES;\n" +
			"DROP TABLE MMOHOROV.PLAYS_FOR;\n" +
			"DROP TABLE MMOHOROV.SEASONS;\n" +
			"DROP TABLE MMOHOROV.TEAMS;\n" +
			"DROP TABLE MMOHOROV.PLAYERS;\n";

	public static final String C_VIEWS =
		"CREATE VIEW PLAYER_SEASON_STATS (\n" +
			"    PLAYER_ID,\n" +
			"    SEASON_ID,\n" +
			"    PLAYER_FNAME,\n" +
			"    PLAYER_LNAME,\n" +
			"    AB_AVG, R_AVG,\n" +
			"    RBI_AVG,\n" +
			"    \"1B_AVG\",\n" +
			"    \"2B_AVG\",\n" +
			"    \"3B_AVG\",\n" +
			"    \"HR_AVG\",\n" +
			"    H,\n" +
			"    BA)\n" +
			"AS\n" +
			"  SELECT\n" +
			"    pi.PLAYER_ID,\n" +
			"    SEASONS.ID,\n" +
			"    PLAYERS.FIRST_NAME,\n" +
			"    PLAYERS.LAST_NAME,\n" +
			"    avg(s.AB),\n" +
			"    avg(s.R),\n" +
			"    avg(s.RBI),\n" +
			"    avg(s.\"1B\"),\n" +
			"    avg(s.\"2B\"),\n" +
			"    avg(s.\"3B\"),\n" +
			"    avg(s.HR),\n" +
			"    sum(s.\"1B\") + sum(s.\"2B\") + sum(s.\"3B\") + sum(s.HR),\n" +
			"    (sum(s.\"1B\") + sum(s.\"2B\") + sum(s.\"3B\") + sum(s.HR) ) / sum(s.AB)\n" +
			"  FROM PERFORMED_IN pi\n" +
			"  LEFT JOIN STATISTICS s ON pi.STATISTIC_ID=s.ID\n" +
			"    INNER JOIN GAMES\n" +
			"      ON pi.GAME_ID = GAMES.ID\n" +
			"    INNER JOIN SEASONS\n" +
			"      ON SEASONS.ID = GAMES.SEASON_ID\n" +
			"    RIGHT OUTER JOIN PLAYERS\n" +
			"      ON pi.PLAYER_ID = PLAYERS.ID\n" +
			"  GROUP BY pi.PLAYER_ID, SEASONS.ID, PLAYERS.FIRST_NAME, PLAYERS.LAST_NAME\n" +
			"  ORDER BY pi.PLAYER_ID, SEASONS.ID\n" +
			"  WITH READ ONLY;\n" +
			"\n" +
			"CREATE VIEW PLAYER_CAREER_STATS (\n" +
			"    PLAYER_ID,\n" +
			"    PLAYER_FNAME,\n" +
			"    PLAYER_LNAME,\n" +
			"    AB_CAREER,\n" +
			"    R_CAREER,\n" +
			"    RBI_CAREER,\n" +
			"    \"1B_CAREER\",\n" +
			"    \"2B_CAREER\",\n" +
			"    \"3B_CAREER\",\n" +
			"    \"HR_CAREER\",\n" +
			"    \"H_CAREER\",\n" +
			"    \"BA_CAREER\"\n" +
			") AS\n" +
			"  SELECT\n" +
			"    PLAYER_ID,\n" +
			"    PLAYER_FNAME,\n" +
			"    PLAYER_LNAME,\n" +
			"    avg(AB_AVG),\n" +
			"    avg(R_AVG),\n" +
			"    avg(RBI_AVG),\n" +
			"    avg(\"1B_AVG\"),\n" +
			"    avg(\"2B_AVG\"),\n" +
			"    avg(\"3B_AVG\"),\n" +
			"    avg(HR_AVG),\n" +
			"    avg(H),\n" +
			"    avg(BA)\n" +
			"  FROM PLAYER_SEASON_STATS\n" +
			"  GROUP BY PLAYER_ID, PLAYER_FNAME, PLAYER_LNAME\n" +
			"  ORDER BY PLAYER_LNAME, PLAYER_FNAME, PLAYER_ID;\n" +
			"\n" +
			"CREATE VIEW TEAM_WINS_BY_SEASON (\n" +
			"    TEAM_ID,\n" +
			"    TEAM_NAME,\n" +
			"    SEASON_ID,\n" +
			"    WINS_PER_SEASON\n" +
			") AS\n" +
			"  SELECT\n" +
			"    TEAMS.ID,\n" +
			"    TEAMS.NAME,\n" +
			"    SEASON_ID,\n" +
			"    COUNT(WINNING_TEAM_ID) AS WINS\n" +
			"  FROM TEAMS\n" +
			"    JOIN (\n" +
			"      SELECT\n" +
			"        GAME_ID,\n" +
			"        SEASON_ID,\n" +
			"        HOME_TEAM_ID,\n" +
			"        VISITOR_TEAM_ID,\n" +
			"        CASE WHEN RUN_DIFFERENTIAL > 0\n" +
			"          THEN HOME_TEAM_ID\n" +
			"        WHEN RUN_DIFFERENTIAL < 0\n" +
			"          THEN VISITOR_TEAM_ID\n" +
			"        ELSE NULL END WINNING_TEAM_ID\n" +
			"      FROM (\n" +
			"        SELECT\n" +
			"          GAMES.ID                               AS GAME_ID,\n" +
			"          GAMES.SEASON_ID                        AS SEASON_ID,\n" +
			"          GAMES.HOME_TEAM_ID                     AS HOME_TEAM_ID,\n" +
			"          GAMES.VISITOR_TEAM_ID                  AS VISITOR_TEAM_ID,\n" +
			"          GAMES.HOME_SCORE                       AS HOME_SCORE,\n" +
			"          GAMES.VISITOR_SCORE                    AS VISITOR_SCORE,\n" +
			"          GAMES.HOME_SCORE - GAMES.VISITOR_SCORE AS RUN_DIFFERENTIAL\n" +
			"        FROM GAMES\n" +
			"      )\n" +
			"      )\n" +
			"      ON TEAMS.ID = WINNING_TEAM_ID\n" +
			"  GROUP BY TEAMS.ID, TEAMS.NAME, SEASON_ID\n" +
			"  ORDER BY SEASON_ID, TEAMS.ID;\n" +
			"\n" +
			"CREATE VIEW TEAM_LOSSES_BY_SEASON (\n" +
			"    TEAM_ID,\n" +
			"    TEAM_NAME,\n" +
			"    SEASON_ID,\n" +
			"    LOSSES_PER_SEASON\n" +
			") AS\n" +
			"  SELECT\n" +
			"    TEAMS.ID,\n" +
			"    TEAMS.NAME,\n" +
			"    SEASON_ID,\n" +
			"    COUNT(LOSING_TEAM_ID) AS LOSSES\n" +
			"  FROM TEAMS\n" +
			"    JOIN (\n" +
			"      SELECT\n" +
			"        GAME_ID,\n" +
			"        SEASON_ID,\n" +
			"        HOME_TEAM_ID,\n" +
			"        VISITOR_TEAM_ID,\n" +
			"        CASE WHEN RUN_DIFFERENTIAL < 0\n" +
			"          THEN HOME_TEAM_ID\n" +
			"        WHEN RUN_DIFFERENTIAL > 0\n" +
			"          THEN VISITOR_TEAM_ID\n" +
			"        ELSE NULL END LOSING_TEAM_ID\n" +
			"      FROM (\n" +
			"        SELECT\n" +
			"          GAMES.ID                               AS GAME_ID,\n" +
			"          GAMES.SEASON_ID                        AS SEASON_ID,\n" +
			"          GAMES.HOME_TEAM_ID                     AS HOME_TEAM_ID,\n" +
			"          GAMES.VISITOR_TEAM_ID                  AS VISITOR_TEAM_ID,\n" +
			"          GAMES.HOME_SCORE                       AS HOME_SCORE,\n" +
			"          GAMES.VISITOR_SCORE                    AS VISITOR_SCORE,\n" +
			"          GAMES.HOME_SCORE - GAMES.VISITOR_SCORE AS RUN_DIFFERENTIAL\n" +
			"        FROM GAMES\n" +
			"      )\n" +
			"      )\n" +
			"      ON TEAMS.ID = LOSING_TEAM_ID\n" +
			"  GROUP BY TEAMS.ID, TEAMS.NAME, SEASON_ID\n" +
			"  ORDER BY SEASON_ID, TEAMS.ID;\n";

	public static final String D_VIEWS =
		"DROP VIEW PLAYER_CAREER_STATS;\n" +
			"DROP VIEW PLAYER_SEASON_STATS;\n" +
			"DROP VIEW TEAM_WINS_BY_SEASON;\n" +
			"DROP VIEW TEAM_LOSSES_BY_SEASON;\n";


	public static void addBatchQuery(String multiQuery, Statement statement) throws SQLException {
		for (String query : multiQuery.split(";"))
			statement.addBatch(query);
	}
}
