
ACCEPT i_player NUMBER PROMPT 'Player Id: '
ACCEPT i_game NUMBER PROMPT 'Game Id: '
ACCEPT i_ab NUMBER PROMPT 'AB: '
ACCEPT i_h NUMBER PROMPT 'H: '
ACCEPT i_r NUMBER PROMPT 'R: '
ACCEPT i_rbi NUMBER PROMPT 'RBI: '
ACCEPT i_1b NUMBER PROMPT '1B: '
ACCEPT i_2b NUMBER PROMPT '2B: '
ACCEPT i_3b NUMBER PROMPT '3B: '
ACCEPT i_hr NUMBER PROMPT 'HR: '

INSERT INTO STATISTICS (PLAYER_ID, GAME_ID, AB, H, R, RBI, "1B", "2B", "3B", HR) VALUES (&i_player, &i_game, &i_ab, &i_h, &i_r, &i_rbi, &i_1b, &i_2b, &i_3b, &i_hr);
EXIT
