
-- team table generation
CREATE TABLE MMOHOROV.TEAMS
(
  id INT PRIMARY KEY NOT NULL,
  name VARCHAR(25)
);


-- player table generation
CREATE TABLE MMOHOROV.PLAYERS
(
  id INT PRIMARY KEY NOT NULL,
  first_name VARCHAR(25),
  last_name VARCHAR(25)
);


-- season table generation
CREATE TABLE MMOHOROV.SEASONS
(
  id INT PRIMARY KEY,
  year INT NOT NULL,
  type VARCHAR(10) NOT NULL
);


-- plays_for table generation
CREATE TABLE MMOHOROV.PLAYS_FOR
(
  PLAYER_ID INT,
  SEASON_ID INT,
  TEAM_ID INT,
  CONSTRAINT PLAY PRIMARY KEY (PLAYER_ID, TEAM_ID, SEASON_ID),
  CONSTRAINT PLAYER_ID FOREIGN KEY (PLAYER_ID) REFERENCES PLAYERS (ID),
  CONSTRAINT SEASON_ID FOREIGN KEY (SEASON_ID) REFERENCES SEASONS (ID),
  CONSTRAINT TEAM_ID FOREIGN KEY (TEAM_ID) REFERENCES TEAMS (ID)
);


CREATE TABLE MMOHOROV.GAMES
(
  ID INT PRIMARY KEY NOT NULL,
  HOME_TEAM_ID INT NOT NULL,
  VISITOR_TEAM_ID INT NOT NULL,
  SEASON_ID INT NOT NULL,
  HOME_SCORE INT NOT NULL,
  VISITOR_SCORE INT NOT NULL,
  GAME_LOCATION VARCHAR2(50) NOT NULL,
  GAME_DATE TIMESTAMP NOT NULL,
  CONSTRAINT HOME_TEAM_ID FOREIGN KEY (HOME_TEAM_ID) REFERENCES TEAMS (ID),
  CONSTRAINT VISITOR_TEAM_ID FOREIGN KEY (VISITOR_TEAM_ID) REFERENCES TEAMS (ID),
  CONSTRAINT SEASON_ID FOREIGN KEY (SEASON_ID) REFERENCES SEASONS (ID)
);


-- creating STATISTICS table code
CREATE TABLE MMOHOROV.STATISTICS
(
  PLAYER_ID INT NOT NULL,
  GAME_ID INT NOT NULL,
  AB INT NOT NULL,
  R INT NOT NULL,
  RBI INT NOT NULL,
  "1B" INT NOT NULL,
  "2B" INT NOT NULL,
  "3B" INT NOT NULL,
  HR INT NOT NULL,
  CONSTRAINT STATISTICS_ID PRIMARY KEY (PLAYER_ID, GAME_ID),
  CONSTRAINT PLAYER_ID FOREIGN KEY (PLAYER_ID) REFERENCES PLAYERS (ID),
  CONSTRAINT GAME_ID FOREIGN KEY (GAME_ID) REFERENCES GAMES (ID)
);